# Change these first
owner: shawngao-org # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: File share
    url: https://file.sgtu.org/
  - name: Dev tools
    url: https://tool.sgtu.org/
  - name: Minecraft Skin
    url: https://skin.sgtu.org/
  - name: Nexus
    url: https://nexus.sgtu.org/
  - name: Gravatar proxy
    url: https://gravatar.shawngao.org/
  - name: DE-BGP-6C24G-1000M
    url: 5.180.253.208
    port: 22
    check: "tcp-ping"
    ipv6: false
  - name: US-BGP-2C6G-50M
    url: 103.150.214.129
    port: 22
    check: "tcp-ping"
    ipv6: false
  - name: CN-BGP-4C4G-10M
    url: 103.36.220.245
    port: 22
    check: "tcp-ping"
    ipv6: false
  - name: CN-CT-2C4G-500M
    url: 110.42.109.248
    port: 22
    check: "tcp-ping"
    ipv6: false
i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: s.sgtu.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.gitmirror.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Service Status
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
